# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
  displayName: 'dotnet test'   

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: tool
    arguments: install dotnet-reportgenerator-globaltool -g
  displayName: 'Install ReportGenerator Global Tool'

- task: DotNetCoreCLI@2
  inputs:
    projects: 'test/**/*.csproj'
    command: custom
    custom: reportgenerator
    arguments: '-reports:$(Build.SourcesDirectory)/test/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage'
  displayName: 'Generating code coverage report'  

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
  displayName: 'Publish code coverage'
